server:
  port: 8100
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://42.192.49.234:3306/flash_gateway?characterEncoding=utf-8&useSSL=false
    username: root
    password: hust123456
  application:
    name: The-Flash # 闪电侠
  cloud:
    zookeeper:
      discovery:
        root: /flash_gateway  # 注册到zk上的根目录默认路径为 /services
      connect-string: 42.192.49.234:2181
    gateway:
      routes:
#      - id: neo_route
#        uri: http://www.ityouknow.com
#        predicates:
#          - Path=/spring-cloud
#      - id: rate.limit.test.api
#        uri: http://localhost:8100/test/rate/test/
#        predicates:
#          - Path=/gateway/rateTest
#        filters:
#          - name: RateLimit
#            args:
#              keys: apiId
#      - id: log_record
#        uri: http://localhost:8100/test/logRecord/
#        predicates:
#          - Path=/logRecord
#        filters:
#          - name: AddCorsHeader
#            args: {
#              "allowOrigin": "*",
#              "allowMethod": "GET",
#              "allowCredentials": "true",
#              "allowHeaders": "*"
#            }
#          - name: LogRecord
#            args:
#              appKey: logRecord
#      - id: grpc_transfer_account
#        uri: grpc://grpc.server.grpc_TransferAccountService/transferAccount    #grpc在zk上注册的路由路径/具体的服务名称
#        predicates:
#          - Path=/transferAccount
#      - id: quota.limit.test.api
#        uri: http://localhost:8100/test/quota/test/
#        predicates:
#          - Path=/gateway/quotaTest
#        filters:
#          - name: QuotaLimit
#            args:
#              keys: userId;appkey,token

# 动态路由配置
management:
  endpoints:
    web:
      exposure:
        include: "*"

# mysql相关配置

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fast.gateway.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
